### ISSUE TITLE
Decouple MagicPacket with TargetEndpoint

### ISSUE THREAD

**Issue by Emilkens** [Emilkens/WakeDevice#4]
`MagicPacket` and `TargetEndpoint` classes are know tightly coupled due to `TargetEndpoint.Wake(...)` method taking object of type `MagicPacket` as a parameter. It is rather unlikely that the app would use different type of packet in the future, though it is now inconvinent to unit test `TargetEndpoint` class.

**Comment by thresiukiewicz** [comment]
resolved in #6 - wake method can now take packet as pure byte data, it should be possible to unit test or reuse it for different packets in the future
